version: "3.8"

services:
  nestednotation:
    build: .
    ports:
      - "3001:3001"
      - "2382:2382"
      - "2381:2381"
      - "2811:2811"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      # Persist account data
      - ./account:/app/account
      # Optional: mount environment files
      - ./.env.development:/app/.env.development:ro
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "0.1"
        reservations:
          memory: 1024M
          cpus: "0.1"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
